version: '3.8'

services:
  # Qdrant for testing
  qdrant-test:
    image: qdrant/qdrant:v1.7.4
    container_name: qdrant-test
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    tmpfs:
      - /qdrant/storage
    networks:
      - test-network

  # Redis for testing
  redis-test:
    image: redis:7.2-alpine
    container_name: redis-test
    ports:
      - "6379:6379"
    networks:
      - test-network

  # Elasticsearch for testing
  elasticsearch-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-test
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    tmpfs:
      - /usr/share/elasticsearch/data
    networks:
      - test-network

networks:
  test-network:
    driver: bridge