name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -v --cov=src/

      - name: Build Docker image
        run: |
          docker build -t deepmu-app:latest .

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker tag deepmu-app:latest docker.io/harigithub11/deepmu:latest
          docker push docker.io/harigithub11/deepmu:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production
      deployment: production

    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/production-deployment.yaml